
Map:   0%|          | 0/164 [00:00<?, ? examples/s]
Map: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 164/164 [00:00<00:00, 4060.91 examples/s]

Map:   0%|          | 0/164 [00:00<?, ? examples/s]
Map: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 164/164 [00:00<00:00, 5128.85 examples/s]
[1;36m(VllmWorkerProcess pid=3169241)[0;0m Error while downloading from https://cdn-lfs-us-1.hf.co/repos/38/b5/38b5db11a3e7f687770cf00c51cb2dc8f8d0ce034fbf527c02c78fb4eec47841/81a100df124c214b152de6471a361015a8e03c2597f21e1471935d7365ed71a1?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27model-00008-of-00017.safetensors%3B+filename%3D%22model-00008-of-00017.safetensors%22%3B&Expires=1739329071&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTczOTMyOTA3MX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zLzM4L2I1LzM4YjVkYjExYTNlN2Y2ODc3NzBjZjAwYzUxY2IyZGM4ZjhkMGNlMDM0ZmJmNTI3YzAyYzc4ZmI0ZWVjNDc4NDEvODFhMTAwZGYxMjRjMjE0YjE1MmRlNjQ3MWEzNjEwMTVhOGUwM2MyNTk3ZjIxZTE0NzE5MzVkNzM2NWVkNzFhMT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=pwDsHufUcSM3kCWmZbNAh3V7sQjlNqBDh1%7ENz0whGpdkuVxA1LlWECH0o5NJ99ggV1bL1VHOpVpVLlfDcdgf41qK%7E%7Ec8wvozT5U5VAnyilA9b-QBdbxo1QrssKof8UNIk0o%7E9EMGPQ2KRAS1dVysRU7rDYoKVpyIAksZ6tBDSKguTiq5PhlVaNWI8TuLRxGJJi1aQwPWkqVSNw%7E2ED8p4TYpHcS-N%7EXOSFK5Amiy5efKVd1TI-mVLYOELGKNo1lIjF1Z-r3L0okYl1jhvQ3SJ7AnbKrhCe-Kfj1zSn9NTx6%7E1r-ePtBQJKxK-Fgefahrlc2fvri3SqXlSs1HHpnskg__&Key-Pair-Id=K24J24Z295AEI9: HTTPSConnectionPool(host='cdn-lfs-us-1.hf.co', port=443): Read timed out.
[1;36m(VllmWorkerProcess pid=3169241)[0;0m Trying to resume download...
[1;36m(VllmWorkerProcess pid=3169242)[0;0m Ignored error while writing commit hash to /home/jingyang22/.cache/huggingface/hub/models--Qwen--QwQ-32B-Preview/refs/main: [Errno 122] Disk quota exceeded.
Ignored error while writing commit hash to /home/jingyang22/.cache/huggingface/hub/models--Qwen--QwQ-32B-Preview/refs/main: [Errno 122] Disk quota exceeded.
[1;36m(VllmWorkerProcess pid=3169243)[0;0m Ignored error while writing commit hash to /home/jingyang22/.cache/huggingface/hub/models--Qwen--QwQ-32B-Preview/refs/main: [Errno 122] Disk quota exceeded.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/net/scratch/jingyang/ShorterBetter/eval/Coding/human_eval/evaluate_human_eval.py", line 113, in <module>
[rank0]:     completions = generate_sample_batch(problems["instruction"])
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/net/scratch/jingyang/ShorterBetter/eval/Coding/human_eval/evaluate_human_eval.py", line 34, in generate_sample_batch
[rank0]:     llm = LLM(
[rank0]:           ^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/utils.py", line 1039, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/entrypoints/llm.py", line 240, in __init__
[rank0]:     self.llm_engine = self.engine_class.from_engine_args(
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 482, in from_engine_args
[rank0]:     engine = cls(
[rank0]:              ^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 271, in __init__
[rank0]:     self.model_executor = executor_class(vllm_config=vllm_config, )
[rank0]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 260, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 49, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/executor/mp_distributed_executor.py", line 123, in _init_executor
[rank0]:     self._run_workers("load_model",
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/executor/mp_distributed_executor.py", line 183, in _run_workers
[rank0]:     driver_worker_output = run_method(self.driver_worker, sent_method,
[rank0]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/utils.py", line 2208, in run_method
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/worker/worker.py", line 182, in load_model
[rank0]:     self.model_runner.load_model()
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/worker/model_runner.py", line 1113, in load_model
[rank0]:     self.model = get_model(vllm_config=self.vllm_config)
[rank0]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/model_executor/model_loader/__init__.py", line 12, in get_model
[rank0]:     return loader.load_model(vllm_config=vllm_config)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/model_executor/model_loader/loader.py", line 380, in load_model
[rank0]:     loaded_weights = model.load_weights(
[rank0]:                      ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/model_executor/models/qwen2.py", line 513, in load_weights
[rank0]:     return loader.load_weights(weights)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/model_executor/models/utils.py", line 233, in load_weights
[rank0]:     autoloaded_weights = set(self._load_module("", self.module, weights))
[rank0]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/model_executor/models/utils.py", line 185, in _load_module
[rank0]:     for child_prefix, child_weights in self._groupby_prefix(weights):
[rank0]:                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/model_executor/models/utils.py", line 99, in _groupby_prefix
[rank0]:     for prefix, group in itertools.groupby(weights_by_parts,
[rank0]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/model_executor/models/utils.py", line 97, in <genexpr>
[rank0]:     for weight_name, weight_data in weights)
[rank0]:                                     ^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/model_executor/model_loader/loader.py", line 355, in _get_all_weights
[rank0]:     yield from self._get_weights_iterator(primary_weights)
[rank0]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/model_executor/model_loader/loader.py", line 308, in _get_weights_iterator
[rank0]:     hf_folder, hf_weights_files, use_safetensors = self._prepare_weights(
[rank0]:                                                    ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/model_executor/model_loader/loader.py", line 261, in _prepare_weights
[rank0]:     hf_folder = download_weights_from_hf(
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/vllm/model_executor/model_loader/weight_utils.py", line 255, in download_weights_from_hf
[rank0]:     hf_folder = snapshot_download(
[rank0]:                 ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/huggingface_hub/_snapshot_download.py", line 296, in snapshot_download
[rank0]:     thread_map(
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
[rank0]:     return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
[rank0]:     return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/tqdm/std.py", line 1169, in __iter__
[rank0]:     for obj in iterable:
[rank0]:                ^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
[rank0]:     yield _result_or_cancel(fs.pop())
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
[rank0]:     return fut.result(timeout)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/concurrent/futures/_base.py", line 456, in result
[rank0]:     return self.__get_result()
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
[rank0]:     raise self._exception
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/concurrent/futures/thread.py", line 59, in run
[rank0]:     result = self.fn(*self.args, **self.kwargs)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/huggingface_hub/_snapshot_download.py", line 270, in _inner_hf_hub_download
[rank0]:     return hf_hub_download(
[rank0]:            ^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 860, in hf_hub_download
[rank0]:     return _hf_hub_download_to_cache_dir(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1009, in _hf_hub_download_to_cache_dir
[rank0]:     _download_to_tmp_and_move(
[rank0]:   File "/home/jingyang22/.conda/envs/rp/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1531, in _download_to_tmp_and_move
[rank0]:     with incomplete_path.open("ab") as f:
[rank0]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: OSError: [Errno 122] Disk quota exceeded
[rank0]:[W211 20:02:53.022871827 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
/home/jingyang22/.conda/envs/rp/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/var/spool/slurmd/job371711/slurm_script: line 164: syntax error near unexpected token `done'
/var/spool/slurmd/job371711/slurm_script: line 164: `done'
